# Generated by Django 3.2.18 on 2023-04-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_crearcurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crearCurso',
        ),
    ]
